version: '2'

services:
    frontend:
        build: ./frontend/
        ports:
         - "8080:80"
        depends_on:
         - api
    api:
        image: shoppingcart:api
        ports: 
         - "3000:3000"